version: '3.9'

services:
  api:
    build:
      context: .
    image: mmashtaler/test_docker:test
    ports:
      - 80:8080
    restart: always
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=flask_app
      - POSTGRES_PASSWORD=flask_app_password
      - POSTGRES_DB=flask_app


